# -*- coding: utf-8 -*-
"""Capstone.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pYNST1UWgaRAT4gMp0FBp6SskrAvzaRc

## 0. Installing Huggin Face's Transformers and Loading Dependencies
"""

from business_logic import get_summary, get_transcript, chunk_sentences, preprocess_transcript
import streamlit as st

st.title("📺 YouTube Video Summarizer")

video_url = st.text_input("🔗 Enter YouTube Video URL:")

if st.button("🎯 Generate Summary"):
    if video_url:
        try:
            transcript = get_transcript(video_url)
            sentences = preprocess_transcript(transcript)
            chunks = chunk_sentences(sentences)
            summary = get_summary(chunks)

            st.subheader("📝 Summary:")
            st.write(summary)
        except Exception as e:
            st.error(f"⚠️ Error: {e}")
    else:
        st.warning("⚠️ Please enter a valid YouTube URL.")

